version: '3.3'

volumes:
 prometheus_data: {}
 grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring

  redis:
    image: redis
    ports:
      - "6379:6379"

  benthos-lab:
    image: jeffail/benthos-lab
    command:
      - '--www=/var/www'
      - '--redis-url=tcp://redis:6379'
      - '--redis-ttl=72h'
    ports:
      - 8080:8080
      - 8081:8081
